# Generated by Django 5.1 on 2024-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_sender_message_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.CharField(max_length=255),
        ),
    ]
