# Generated by Django 5.1 on 2024-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_color_alter_message_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
