# Generated by Django 5.1 on 2024-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='color',
            field=models.CharField(default='#f1f1f1', max_length=7),
        ),
    ]
